// bookshelf/data.jsx — mock users, books, passports, threads, neighbours.

const USERS = {
  me: {
    id: 'me',
    name: 'Sophie Martin',
    photo: 'https://i.pravatar.cc/150?img=47',
    bio: 'Bibliophile, coffee addict, and proud resident of Alfama. Always happy to swap a good story!',
    district: 'Alfama',
    city: 'Lisbon',
    country: '🇵🇹',
  },
  u1: {
    id: 'u1',
    name: 'Carlos Mendes',
    photo: 'https://i.pravatar.cc/150?img=12',
    bio: 'History lover and weekend cyclist. My shelf is full of biographies and travel stories. Happy to meet at Miradouro da Graça!',
    district: 'Mouraria',
    city: 'Lisbon',
    country: '🇵🇹',
  },
  u2: {
    id: 'u2',
    name: 'Ana Ferreira',
    photo: 'https://i.pravatar.cc/150?img=45',
    bio: 'Literature teacher who believes books belong in as many hands as possible. Specialist in magical realism.',
    district: 'Bairro Alto',
    city: 'Lisbon',
    country: '🇵🇹',
  },
  u3: {
    id: 'u3',
    name: 'Lucas Weber',
    photo: 'https://i.pravatar.cc/150?img=15',
    bio: 'Expat from Berlin, collecting stories from around the world one page at a time. Fluent in four languages.',
    district: 'Príncipe Real',
    city: 'Lisbon',
    country: '🇩🇪',
  },
  u4: {
    id: 'u4',
    name: 'Maria Santos',
    photo: 'https://i.pravatar.cc/150?img=38',
    bio: 'Interior designer with a passion for literary fiction and architecture books. My shelf is colourful and eclectic.',
    district: 'Alfama',
    city: 'Lisbon',
    country: '🇵🇹',
  },
  u5: {
    id: 'u5',
    name: 'Tomás Oliveira',
    photo: 'https://i.pravatar.cc/150?img=8',
    bio: 'Retired teacher, voracious reader, very friendly. Come pick up a book, stay for a chat and a coffee.',
    district: 'Graça',
    city: 'Lisbon',
    country: '🇵🇹',
  },
};

const BOOKS = [
  {
    id: 'b1',
    isbn: '9780525559474',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    seller: 'u1',
    price: 5,
    free: false,
    condition: 'As New',
    genre: 'Fiction',
    rating: 5,
    review: 'A life-changing read. Nora\'s journey made me rethink everything I thought I knew about regret and possibility.',
    passport: [
      { user: 'u3', country: '🇩🇪', city: 'Berlin', date: 'Mar 2023', rating: 5, note: 'Found this at a little bookshop near Hackescher Markt. Devoured it in one sitting on the train to Hamburg.' },
      { user: 'u2', country: '🇵🇹', city: 'Porto', date: 'Jul 2023', rating: 4, note: 'A beautiful concept. I wept at the end and immediately wanted to re-read it.' },
      { user: 'u1', country: '🇵🇹', city: 'Lisbon', date: 'Jan 2024', rating: 5, note: 'A life-changing read. Nora\'s journey made me rethink everything I thought I knew about regret and possibility.' },
    ],
  },
  {
    id: 'b2',
    isbn: '9780375704024',
    title: 'Norwegian Wood',
    author: 'Haruki Murakami',
    seller: 'u2',
    price: 0,
    free: true,
    condition: 'Used',
    genre: 'Literary Fiction',
    rating: 5,
    review: 'Murakami at his most tender. I\'ve read this three times and each time it hits differently.',
    passport: [
      { user: 'u5', country: '🇵🇹', city: 'Lisbon', date: 'Apr 2022', rating: 5, note: 'My daughter gave me this. I cried twice, in the best possible way.' },
      { user: 'u2', country: '🇵🇹', city: 'Lisbon', date: 'Nov 2023', rating: 5, note: 'Murakami at his most tender. I\'ve read this three times and each time it hits differently.' },
    ],
  },
  {
    id: 'b3',
    isbn: '9780061122415',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    seller: 'u3',
    price: 4,
    free: false,
    condition: 'Quite Old',
    genre: 'Adventure',
    rating: 4,
    review: 'A legend for good reason. Read it slowly, one page at a time, and let it find you.',
    passport: [
      { user: 'u4', country: '🇵🇹', city: 'Faro', date: 'Jun 2021', rating: 4, note: 'My travel companion through the Algarve. Read it on the beach at sunset.' },
      { user: 'u1', country: '🇵🇹', city: 'Lisbon', date: 'Sep 2022', rating: 5, note: 'Still magical, even after all this time. Some books get better with age.' },
      { user: 'u3', country: '🇩🇪', city: 'Munich', date: 'Feb 2023', rating: 4, note: 'A legend for good reason. Read it slowly, one page at a time, and let it find you.' },
    ],
  },
  {
    id: 'b4',
    isbn: '9780735211292',
    title: 'Atomic Habits',
    author: 'James Clear',
    seller: 'u4',
    price: 8,
    free: false,
    condition: 'As New',
    genre: 'Self-Help',
    rating: 4,
    review: 'Genuinely changed how I approach my daily routines. The 1% rule is something I think about every morning.',
    passport: [
      { user: 'u4', country: '🇵🇹', city: 'Lisbon', date: 'Mar 2024', rating: 4, note: 'Genuinely changed how I approach my daily routines. The 1% rule is something I think about every morning.' },
    ],
  },
  {
    id: 'b5',
    isbn: '9780156012195',
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    seller: 'u5',
    price: 0,
    free: true,
    condition: 'Used',
    genre: 'Classic',
    rating: 5,
    review: 'For adults who remember being children. A gift to the world that never stops giving.',
    passport: [
      { user: 'u2', country: '🇫🇷', city: 'Paris', date: 'Jan 2019', rating: 5, note: 'Read this as a child, found it again in a Seine-side bouquiniste. Some books are lifelong companions.' },
      { user: 'u3', country: '🇧🇪', city: 'Brussels', date: 'May 2020', rating: 5, note: 'Shared with my whole family during lockdown. It made us all a little softer.' },
      { user: 'u1', country: '🇵🇹', city: 'Lisbon', date: 'Aug 2022', rating: 5, note: 'This book makes the world a bit softer. Pass it on.' },
      { user: 'u5', country: '🇵🇹', city: 'Sintra', date: 'Dec 2023', rating: 5, note: 'For adults who remember being children. A gift to the world that never stops giving.' },
    ],
  },
  {
    id: 'b6',
    isbn: '9780062316097',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    seller: 'u1',
    price: 7,
    free: false,
    condition: 'Used',
    genre: 'History',
    rating: 4,
    review: 'Puts everything in perspective. Humbling and fascinating in equal measure — essential reading for the curious.',
    passport: [
      { user: 'u3', country: '🇬🇧', city: 'London', date: 'Oct 2021', rating: 5, note: 'Read this on a rainy weekend in London. Could not put it down. Changed how I see history.' },
      { user: 'u1', country: '🇵🇹', city: 'Lisbon', date: 'Apr 2023', rating: 4, note: 'Puts everything in perspective. Humbling and fascinating in equal measure.' },
    ],
  },
  {
    id: 'b7',
    isbn: '9780571334650',
    title: 'Normal People',
    author: 'Sally Rooney',
    seller: 'u2',
    price: 6,
    free: false,
    condition: 'As New',
    genre: 'Literary Fiction',
    rating: 4,
    review: 'Rooney captures the ache of being young with uncomfortable precision. You\'ll recognise yourself on every page.',
    passport: [
      { user: 'u4', country: '🇮🇪', city: 'Dublin', date: 'Jul 2022', rating: 4, note: 'Read this visiting my cousin in Dublin. Felt very Irish, in the best way.' },
      { user: 'u2', country: '🇵🇹', city: 'Lisbon', date: 'Jan 2024', rating: 4, note: 'Rooney captures the ache of being young with uncomfortable precision.' },
    ],
  },
  {
    id: 'b8',
    isbn: '9780399590504',
    title: 'Educated',
    author: 'Tara Westover',
    seller: 'u3',
    price: 0,
    free: true,
    condition: 'Quite Old',
    genre: 'Memoir',
    rating: 5,
    review: 'Absolutely extraordinary. I was unable to speak for a long time after finishing it. Everyone should read this.',
    passport: [
      { user: 'u5', country: '🇺🇸', city: 'New York', date: 'Aug 2020', rating: 5, note: 'A niece brought this from New York. Passed it to everyone I know. Extraordinary.' },
      { user: 'u2', country: '🇵🇹', city: 'Porto', date: 'Mar 2022', rating: 5, note: 'I stayed up all night to finish this. My heart was in my throat the whole time.' },
      { user: 'u3', country: '🇩🇪', city: 'Hamburg', date: 'Sep 2023', rating: 5, note: 'Absolutely extraordinary. I was unable to speak for a long time after finishing it.' },
    ],
  },
];

const MY_PUBLISHED = [
  {
    id: 'mp1',
    isbn: '9780756404741',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    seller: 'me',
    price: 5,
    free: false,
    condition: 'As New',
    genre: 'Fantasy',
    rating: 5,
    review: 'An instant favourite. Kvothe is one of the great characters in modern fantasy.',
    passport: [
      { user: 'me', country: '🇵🇹', city: 'Lisbon', date: 'Mar 2024', rating: 5, note: 'An instant favourite. Kvothe is one of the great characters in modern fantasy.' },
    ],
  },
  {
    id: 'mp2',
    isbn: '9780441013593',
    title: 'Dune',
    author: 'Frank Herbert',
    seller: 'me',
    price: 0,
    free: true,
    condition: 'Used',
    genre: 'Science Fiction',
    rating: 5,
    review: 'The world-building is simply unparalleled. A masterpiece that rewards re-reading.',
    passport: [
      { user: 'u4', country: '🇸🇦', city: 'Riyadh', date: 'Jan 2020', rating: 5, note: 'A gift from a colleague while travelling for work. The desert scenes felt very real.' },
      { user: 'me', country: '🇵🇹', city: 'Lisbon', date: 'Nov 2023', rating: 5, note: 'The world-building is simply unparalleled. A masterpiece that rewards re-reading.' },
    ],
  },
];

const MY_READING = [
  {
    id: 'mr1',
    isbn: '9780525620792',
    title: 'The Dutch House',
    author: 'Ann Patchett',
    price: 5,
    free: false,
    condition: 'As New',
    passport: [],
  },
];

const THREADS = [
  {
    id: 't1',
    with: 'u1',
    book: 'b1',
    unread: 2,
    request: 'pending',
    messages: [
      { from: 'them', text: 'Hi! I saw your listing for The Midnight Library — is it still available?', time: '10:02' },
      { from: 'me', text: 'Yes it is! In great condition. Are you in Alfama?', time: '10:15' },
      { from: 'them', text: 'Not far — I\'m in Mouraria. Could we meet at the Miradouro da Graça?', time: '10:22' },
      { from: 'them', text: 'I can do Saturday morning if that works for you?', time: '10:23' },
    ],
  },
  {
    id: 't2',
    with: 'u2',
    book: 'b2',
    unread: 0,
    request: null,
    messages: [
      { from: 'them', text: 'Thanks so much for the book! Norwegian Wood was everything you said it would be.', time: 'Yesterday' },
      { from: 'me', text: 'So glad you enjoyed it! Murakami never disappoints 📚', time: 'Yesterday' },
    ],
  },
];

const NEIGHBOURS = [
  { id: 'u1', x: 42, y: 28, count: 4 },
  { id: 'u2', x: 24, y: 55, count: 3 },
  { id: 'u3', x: 65, y: 38, count: 5 },
  { id: 'u4', x: 52, y: 68, count: 2 },
  { id: 'u5', x: 76, y: 22, count: 6 },
];

const ALL_BOOKS = [...BOOKS, ...MY_PUBLISHED, ...MY_READING];
const bookById = (id) => ALL_BOOKS.find(b => b.id === id);
const userById = (id) => USERS[id] || USERS.me;

Object.assign(window, { USERS, BOOKS, MY_PUBLISHED, MY_READING, THREADS, NEIGHBOURS, ALL_BOOKS, bookById, userById });
