// bookshelf/legal-content.jsx — TEMPLATE legal copy. NOT legal advice.
// Placeholders in [brackets] must be completed and the whole reviewed by counsel.

const LAST_UPDATED = '1 June 2026';
const COMPANY = '[Company Legal Name] ("My Bookshelf", "we", "us")';

const TERMS = [
  { h: '1. Who we are & accepting these Terms', p: `These Terms govern your use of the My Bookshelf application operated by ${COMPANY}. By creating an account or using the app you confirm you accept these Terms and our Privacy Policy. If you do not agree, do not use the app.` },
  { h: '2. Eligibility', p: 'You must be at least 16 years old (or the minimum age of digital consent in your country) and able to form a binding contract. You are responsible for keeping your login credentials secure and for all activity under your account.' },
  { h: '3. What My Bookshelf is — and is not', p: 'My Bookshelf is a platform that helps neighbours discover, list, give away, sell and exchange second-hand books and arrange to meet in person. We are a venue and intermediary only. We are NOT a party to any agreement, sale, gift or exchange between users, we do not take ownership of any book, and we do not guarantee the existence, quality, safety, legality or accuracy of any listing.' },
  { h: '4. Listings, prices & free items', p: 'You are solely responsible for your listings, including the description, condition rating, price (in euro) or "free" status, and for ensuring you have the right to sell or give away each book. Book metadata and cover images may be retrieved from third-party sources (e.g. Open Library) and are provided "as is" without warranty of accuracy.' },
  { h: '5. Payments', p: 'Where a price is charged, payments are processed by our third-party payment provider (Stripe). We do not store full card details. You authorise the applicable charges and agree to the payment provider\'s terms. Any dispute about a payment between users must be resolved between those users; we may, but are not obliged to, assist.' },
  { h: '6. In-person exchanges & your safety', p: 'All handovers happen in person between users. YOU ARRANGE AND ATTEND MEETINGS AT YOUR OWN RISK. We strongly recommend meeting in public places during daylight and not sharing your exact home address. We are not responsible or liable for any meeting, conduct, injury, loss, theft or damage arising from interactions between users.' },
  { h: '7. Subscription & free trial', p: 'New accounts may receive a free trial period (currently 3 months from signup). After the trial, continued access to paid features requires a subscription (currently €29/year) billed via our payment provider. Subscriptions renew unless cancelled before the renewal date. Statutory withdrawal/refund rights, where they apply, are respected; otherwise fees are non-refundable except as required by law.' },
  { h: '8. Acceptable use & prohibited items', p: 'You must not: list counterfeit, stolen, illegal, hateful, or age-restricted material; harass or endanger others; post false reviews; scrape or misuse the service; or breach any law. We may remove content and suspend or terminate accounts that violate these Terms.' },
  { h: '9. Your content & the Book Passport', p: 'You retain ownership of content you submit (reviews, notes, photos). You grant us a worldwide, royalty-free licence to host, display and distribute that content within the app, including as part of a book\'s "Passport" (its ownership and review history), which may remain visible to others after a book passes to a new owner. Do not submit content you are not permitted to share.' },
  { h: '10. Disclaimers', p: 'The app is provided "as is" and "as available" without warranties of any kind, whether express or implied, including fitness for a particular purpose, accuracy, or non-infringement. We do not warrant uninterrupted or error-free operation.' },
  { h: '11. Limitation of liability', p: 'To the maximum extent permitted by law, we are not liable for indirect, incidental, special or consequential damages, nor for any loss arising from transactions, meetings, or interactions between users. Our total aggregate liability for any claim is limited to the greater of the fees you paid us in the 12 months before the claim or €50. Nothing limits liability that cannot be excluded by law (e.g. for death or personal injury caused by our negligence, or fraud).' },
  { h: '12. Indemnity', p: 'You agree to indemnify and hold us harmless from claims, losses and costs (including reasonable legal fees) arising from your listings, content, conduct, transactions, or breach of these Terms or any law.' },
  { h: '13. Suspension & termination', p: 'You may close your account at any time. We may suspend or terminate access where we reasonably believe these Terms or the law have been breached, or to protect users or the service.' },
  { h: '14. Changes to these Terms', p: 'We may update these Terms; we will notify you of material changes and, where required, seek your consent. Continued use after changes take effect constitutes acceptance.' },
  { h: '15. Governing law & disputes', p: 'These Terms are governed by the laws of [jurisdiction], and the courts of [jurisdiction] have exclusive jurisdiction, without prejudice to mandatory consumer-protection rights in your country of residence. EU consumers may also use the European Commission\'s Online Dispute Resolution platform.' },
  { h: '16. Contact', p: 'Questions about these Terms: [legal@yourcompany.com] · [registered company address].' },
];

const PRIVACY = [
  { h: '1. Data controller', p: `The controller of your personal data is ${COMPANY}, [registered address]. Data protection contact / DPO: [dpo@yourcompany.com].` },
  { h: '2. Data we collect', p: 'Account & profile: name, photo, short bio, email. Location: your neighbourhood/district and city (we do NOT collect or display your exact address). Activity: listings, reviews, ratings, "passport" entries, messages with other users. Transactions: payment status and limited details via our payment provider (we do not store full card numbers). Technical: device/usage data needed to run and secure the service.' },
  { h: '3. Legal bases (GDPR Art. 6)', p: 'Contract — to create your account and provide the service. Consent — for optional analytics, personalised recommendations, and any non-essential cookies/SDKs; you may withdraw consent at any time. Legitimate interests — to keep the service safe, prevent fraud and improve it (balanced against your rights). Legal obligation — to meet accounting, tax and legal duties.' },
  { h: '4. How we use your data', p: 'To run your account and the marketplace; show books and readers near you (by district, not exact address); enable messaging and in-person handovers; maintain each book\'s Passport; process subscriptions and payments; provide support; ensure safety and comply with law. With your consent, to analyse usage and personalise recommendations.' },
  { h: '5. Who we share it with', p: 'Other users — your public profile, district, listings, reviews and passport entries are visible to other users; your exact address and email are never shown. Processors acting on our instructions — payment (Stripe), hosting, maps, analytics, and book metadata (Open Library). Authorities — where required by law. We do not sell your personal data.' },
  { h: '6. International transfers', p: 'Where data is processed outside your region, we rely on appropriate safeguards such as the European Commission\'s Standard Contractual Clauses or an adequacy decision.' },
  { h: '7. Retention', p: 'We keep personal data only as long as needed for the purposes above or as required by law. When you delete your account we delete or anonymise your personal data; note that Passport entries may be retained in anonymised form to preserve a book\'s history, and limited records may be kept to meet legal obligations.' },
  { h: '8. Your rights', p: 'Subject to law, you may: access a copy of your data; correct inaccurate data; erase your data ("right to be forgotten"); restrict or object to processing; port your data; and withdraw consent at any time. You can exercise these in the app under Privacy & data, or by contacting us. You also have the right to lodge a complaint with your local data protection supervisory authority.' },
  { h: '9. Cookies & similar technologies', p: 'We use storage strictly necessary to run the app, and — only with your consent — optional analytics/personalisation technologies. You can change your choices any time in Privacy & data.' },
  { h: '10. Children', p: 'The app is not intended for users below the minimum digital-consent age in their country. We do not knowingly process such children\'s data.' },
  { h: '11. Security & changes', p: 'We use technical and organisational measures to protect your data. We may update this policy and will notify you of material changes. Contact: [privacy@yourcompany.com].' },
];

Object.assign(window, { LAST_UPDATED, TERMS, PRIVACY });
